# Generated by Django 2.2.14 on 2020-07-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='biography'),
        ),
        migrations.RemoveField(
            model_name='abstractbook',
            name='author',
        ),
        migrations.AddField(
            model_name='abstractbook',
            name='author',
            field=models.ManyToManyField(null=True, to='bookHandler.Author'),
        ),
        migrations.AlterField(
            model_name='abstractbook',
            name='isbn',
            field=models.CharField(help_text='International code (10 or 13 digits)', max_length=13, verbose_name='ISBN'),
        ),
    ]
