# Generated by Django 2.2.14 on 2020-07-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHandler', '0002_auto_20200729_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbook',
            name='author',
            field=models.ManyToManyField(to='bookHandler.Author'),
        ),
    ]
